Converted rc over to python

diff --git a/rc b/rc
--- a/rc
+++ b/rc
@@ -1,102 +1,131 @@
-#!/bin/bash
+#!/usr/bin/python
 #
-# /etc/rc: system boot script
+# System boot script
+# Copyright 2004 Forty-two <http://forty-two.berlios.de>
+# Released under a BSD license
 #
 
-echo "The system is coming up.  Please wait."
+# Variables needed from /etc/rc.conf:
+# timezone
+# hostname
+# font (console font)
+# keymap
+# modules (_ARRAY_ of modules)
 
-# Load configuration
-. /etc/rc.conf
+# Load the system module
+from os import system
+from os import path
 
-# Start device management daemon
-/sbin/devfsd /dev
+print "Forty-two is booting the system...\n"
 
-# Activate swap
-/sbin/swapon -a
+# Here we would normally load rc.conf
+# Since we don't have an rc.conf I'm skipping it
 
-# Mount root read-only
-/bin/mount -n -o remount,ro /
+# Start devfsd below
+# I would have started pts, but I don't know what daemon to start...
+# We will use PTS eventually.
 
-# Check filesystems
-/sbin/fsck -A -T -C -a
-if [ $? -gt 1 ]; then
-	echo
-	echo "***************  FILESYSTEM CHECK FAILED  ******************"
-	echo "*                                                          *"
-	echo "*  Please repair manually and reboot. Note that the root   *"
-	echo "*  file system is currently mounted read-only. To remount  *"
-	echo "*  it read-write type: mount -n -o remount,rw /            *"
-	echo "*  When you exit the maintainance shell the system will    *"
-	echo "*  reboot automatically.                                   *"
-	echo "*                                                          *"
-	echo "************************************************************"
-	echo
-	/sbin/sulogin -p
-	echo "Automatic reboot in progress..."
-	/bin/umount -a
-	/bin/mount -n -o remount,ro /
-	/sbin/reboot -f
-	exit 0
-fi
+system( "/sbin/devfsd /dev" )
 
-# Mount local filesystems
-/bin/mount -n -o remount,rw /
-/bin/rm -f /etc/mtab* 
-/bin/mount -a -O no_netdev
+# Activate swap partition
 
-# Clean up misc files
-: > /var/run/utmp
-/bin/rm -rf /forcefsck /fastboot /etc/nologin /etc/shutdownpid \
-            /var/run/*.pid /var/lock/* /tmp/{.*,*} &> /dev/null
+system( "/sbin/swapon -a" )
+
+# Mount root (/) read-only
+system( "/bin/mount -n -o remount,ro /" )
+
+# Check filesystems for errors
+# This can be commented out to improve boot time
+system( "/sbin/fsck -A -T -C -a" )
+tmp = system( "/bin/echo $?" ) # The shell variable $?
+if tmp > 1: # If the filesystem is bad
+	print "************ ERROR: FILESYSTEM CHECK FAILED *************\n"
+	print "**                                                     **\n"
+	print "** You will now enter a shell to repair this manually. **\n"
+	print "** You will then be rebooted.                          **\n"
+	print "*********************************************************\n"
+	#Give them a shell then reboot the system
+	system( "/sbin/sulogin -p" )
+	print "Forty-two is rebooting the system...\n"
+	system( "/bin/umount -a" )
+	system( "/bin/mount -n -o remount,ro /" )
+	system( "/sbin/reboot -f" )
+	exit # Kill the script
+
+# Mount filesystems
+system( "/bin/mount -n -o remount,rw /" )
+system( "/bin/rm -f /etc/mtab*" )
+system( "/bin/mount -a -O no_netdev" )
+
+# Clean up miscellaneous files
+
+# I don't know what this does so I'm not including it yet
+# When the time comes I'll uncomment it
+# system( "/var/run/utmp" )
+
+system( "/bin/rm -rf /forcefsck /fastboot /etc/nologin /etc/shutdownpid /var/run/*.pid /var/lock/* /tmp/* &> /dev/null" )
 
 # Set kernel variables
-/sbin/sysctl -p > /dev/null
+system( "/sbin/sysctl -p > /dev/null" )
 
 # Update shared library links
-/sbin/ldconfig
+system( "/sbin/ldconfig" )
 
-# Configure host name
-if [ "$HOSTNAME" ]; then
-	echo "hostname: $HOSTNAME"
-	/bin/hostname $HOSTNAME
-fi
+# Configure hostname
+if hostname:
+	print "Setting hostname to",hostname,"\n"
+	#Set the hostname
+	tmp = "/bin/hostname",hostname
+	system( tmp )
 
 # Load random seed
-if [ -f /var/tmp/random-seed ]; then
-	/bin/cat /var/tmp/random-seed > /dev/urandom
-fi
+# Returns true if /var/tmp/random-seed exists
+tmp = path.exists( "/var/tmp/random-seed" )
+if tmp:
+	system( "/bin/cat /var/tmp/random-seed > /dev/urandom" )
 
-# Configure system clock
-if [ ! -f /etc/adjtime ]; then
-	echo "0.0 0 0.0" > /etc/adjtime
-fi
-if [ "$TIMEZONE" ]; then
-	/bin/ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
-fi
-/sbin/hwclock --hctosys
+# Set the clock
+tmp = path.exists( "/etc/adjtime" )
+if tmp:
+	break
+else:
+	system( "/bin/echo \"0.0 0 0.0\" > /etc/adjtime" )
 
+# And set the timezone ;)
+if timezone:
+	tmp = "/bin/ln -sf /usr/share/zoneinfo/" + timezone
+	system( tmp )
+
+system( "/sbin/hwclock --hctosys" )
+
+#
+# Remove this eventually
+# Have it set in rc.conf so they can pick they're system logger
+# Then a /etc/rc.d script to start it
+#
 # Start log daemons
-/usr/sbin/syslogd
-/usr/sbin/klogd -c 4
+system( "/usr/sbin/sysklogd" )
+system( "/usr/sbin/klogd -c 4" )
 
-# Load console font
-if [ "$FONT" ]; then
-	echo "font: $FONT"
-	/usr/bin/setfont $FONT
-fi
+# Load console font (OPTIONAL)
+if font:
+	print "Setting console font to:",font
+	tmp = "/usr/bin/setfont",font
+	system( tmp )
 
-# Load console keymap
-if [ "$KEYMAP" ]; then
-	echo "keyboard: $KEYMAP"
-	/bin/loadkeys -q $KEYMAP
-fi
+if keymap:
+	print "Setting keymap to:",font
+	tmp = "/bin/loadkeys -q",keymap
+	system( tmp )
 
-# Screen blanks after 15 minutes idle time
-/usr/bin/setterm -blank 15
+# After 15 minutes idle, blank the screen
+system( "/usr/bin/setterm -blank 15" )
 
-# Run module initialization script
-if [ -x /etc/rc.modules ]; then
-	/etc/rc.modules
-fi
+# Load modules
+for module in modules:
+	print "Loading module:",module
+	tmp = "/sbin/depmod",module
+	system( tmp )
 
-# End of file
+# End of script
+#
